baseURL = "https://asterane.github.io/the-grid"
languageCode = "en-us"
title = "asterane"
publishDir = "../docs"

[params]
  Name = "The Grid"

[markup.highlight]
  style = "emacs"

[markup.goldmark.renderer]
  unsafe = true
